# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3eb0f04005ab9610b6bb1f54df5086936cc04b01253b382bb6fae2e6ef11141078e90699ea96e5472fbfb146c682454de85811e43cb059b6b0009975cd11c273

test:
  secret_key_base: 3ab10afdcb157942f4ea0a2d7e61718f6bd7133539b8c75c1b3047c08d49c22d71d3ae2a383bd60465243452c98c803aca28b102b1593eca22b4afff1ec18ed3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
